lib/orangetheses/harvester.rb
lib/orangetheses/indexer.rb
spec/harvester_spec.rb
spec/indexer_spec.rb

Pass options to client.list_records

---

lib/orangetheses/indexer.rb
spec/indexer_spec.rb

Adds title_sort

---

lib/orangetheses/indexer.rb
spec/indexer_spec.rb

date, ark, and author_sort enhancements

---

lib/orangetheses.rb
lib/orangetheses/indexer.rb
orangetheses.gemspec
spec/indexer_spec.rb

Closes #4.
I'm going to rebase #6 to include the enhancements there minus the date parsing code.

use chronic gem for more robust date parsing

---

lib/orangetheses/indexer.rb

additional blacklight fields

---

lib/orangetheses.rb
lib/orangetheses/fetcher.rb
lib/orangetheses/indexer.rb
lib/tasks/orangetheses.rake
orangetheses.gemspec
spec/fetcher_spec.rb
spec/indexer_spec.rb

support indexing from dspace REST api

---

lib/orangetheses/indexer.rb
orangetheses.gemspec
spec/indexer_spec.rb

use iso language code for non-english theses

---

lib/orangetheses/indexer.rb
spec/indexer_spec.rb

electronic link display text reflects item access

---

README.md
lib/orangetheses/fetcher.rb
lib/orangetheses/indexer.rb
lib/orangetheses/version.rb
lib/tasks/orangetheses.rake
spec/indexer_spec.rb

Creates rake task to fetch Dataspace theses and store to file for easy adding to Solr.
Makes sure all class year fields included are integers.

Cache theses

---

lib/orangetheses/indexer.rb
orangetheses.gemspec
spec/indexer_spec.rb

add call numbers to theses, include embargo

---

lib/orangetheses/visual.rb
spec/visual_spec.rb

add related names field and call number browse holding field

---

lib/orangetheses/indexer.rb
lib/orangetheses/visual.rb
spec/indexer_spec.rb

Embargoed items have no access. Advances #33 
Makes formats sentence cased. Advances pulibrary/orangelight#665

Capitalization embargo

---

lib/orangetheses/indexer.rb
spec/indexer_spec.rb

embargo only when valid future date is present

---

lib/orangetheses/visual.rb
lib/tasks/orangetheses.rake

For weekly Solr visuals updates.

remove old visuals records before adding new ones

---

lib/orangetheses/fetcher.rb
lib/orangetheses/indexer.rb
spec/fetcher_spec.rb
spec/indexer_spec.rb

2017 update

---

lib/orangetheses/visual.rb
spec/visual_spec.rb

Closes #43.
Also increases rsolr connection timeout.

allow links with redirects to index

---

lib/orangetheses.rb
lib/orangetheses/railtie.rb
lib/orangetheses/version.rb

Add railtie to allow rake tasks to be loaded

---

.circleci/config.yml
circle.yml

Upgrading to CircleCI 2.0

---

.travis.yml
orangetheses.gemspec

Removes travis
Updates bundler

Updates bundler dependency and removes travis

---

lib/orangetheses/indexer.rb
lib/orangetheses/version.rb
spec/indexer_spec.rb
spec/visual_spec.rb

58 alma update physical and electronic

---

lib/orangetheses/indexer.rb
lib/orangetheses/version.rb
spec/indexer_spec.rb

Update library name and location to Mudd Manuscript Library

---

lib/orangetheses/indexer.rb
spec/indexer_spec.rb

i74: Add language_name_display field to solr output

---

config/dspace.yml
config/solr.yml
lib/orangetheses.rb
lib/orangetheses/dataspace_document.rb
lib/orangetheses/fetcher.rb
orangetheses.gemspec
spec/lib/orangetheses/fetcher_api_spec.rb

Providing YAML configuration support for settings used by the DSpace API Fetcher client

---

.circleci/config.yml
lib/orangetheses/dataspace_document.rb
lib/orangetheses/fetcher.rb
lib/orangetheses/indexer.rb
lib/orangetheses/visual.rb

Upgrading to support Ruby 3.2 releases

---

lib/orangetheses/fetcher.rb
orangetheses.gemspec
spec/spec_helper.rb

Remove pry-byebug

---

config/dspace.yml
lib/orangetheses/dataspace_document.rb
lib/orangetheses/fetcher.rb
lib/orangetheses/harvester.rb
lib/orangetheses/indexer.rb
lib/tasks/oai.rake
orangetheses.gemspec
spec/indexer_spec.rb
spec/lib/orangetheses/fetcher_api_spec.rb
spec/lib/orangetheses/harvester_spec.rb
spec/spec_helper.rb

Restructuring the generation of access restriction text during indexing and implementing a Rake Task for indexing OAI Items using a given Set ID

---

lib/orangetheses/fetcher.rb
lib/orangetheses/indexer.rb
spec/indexer_spec.rb

Remove pufields from indexer

---

lib/orangetheses/indexer.rb
spec/indexer_spec.rb

closes #76 
check for class year to add holding
replace 'restrictions_note_display' => restrictions_display_text(values) move the embargo check before the class year check

[#76] Theses before 2012 should not be requestable

---

lib/orangetheses/indexer.rb
spec/indexer_spec.rb

part of #76 
Indexed theses w[ere approved](https://github.com/pulibrary/orangetheses/issues/76#issuecomment-2414692690) by @LynnDurgin

[#76] Embargoed theses should not have a holdings1_display
